### ISSUE TITLE
Great work! Consider using a dense retriever?

### ISSUE THREAD

**Issue by drqiaojin** [som-shahlab/Clinfo.AI#1]
First, thank you for sharing this great study!

I see that the current retrieval uses keyword generation and lexical search by Entrez. Have you considered using dense vectors to perform the retrieval? 

We just released MedCPT, which is a zero-shot biomedical IR model pre-trained by 255M query-article click logs in PubMed search. You can download MedCPT at: https://huggingface.co/ncbi/MedCPT-Query-Encoder and https://huggingface.co/ncbi/MedCPT-Article-Encoder.

Best,
Qiao

**Comment by alejandro-lozano-dev** [comment]
Hey Andy, amazing work! I will add integration with MedCPT soon!

**Comment by alejandro-lozano-dev** [comment]
Hello @Andy-jqa  we have added support for dense retrievers using MedCPT, thanks a lot!
